const fs = require('fs');
const path = require('path');
const { evaluateDocumentChecks, evaluateJudgmentDependentChecks, pendingJudgmentChecklist } = require('../modules/document-checking/checklist');

// Regression harness for document-checking's SOP checklist implementation (see
// JD1_Checklist_SOP_vs_Current_System.md item 3). Each fixture's `extractedFields` and
// `expected` were generated by actually running evaluateDocumentChecks against real or
// deliberately-modified real case data this session, not guessed — see the fixture's own
// `description` for what real case it derives from.
//
// Purpose: this is what SOP items 13-18 (the identity/consistency judgment module) get
// built and validated against, so a new judgment check can be checked for false positives
// against the sample set *before* being promoted from flag to gate — exactly the review
// step identity_consistency's original checks skipped, which is why they had to be
// disabled after shipping straight to a blocking gate.
const FIXTURES_DIR = path.join(__dirname, 'fixtures', 'documentChecking');

const allFixtureFiles = fs.readdirSync(FIXTURES_DIR).filter((f) => f.endsWith('.json'));
// A fixture with a `judgments` key exercises evaluateJudgmentDependentChecks (synthetic
// judgment input, no LLM call) instead of evaluateDocumentChecks — see that function's own
// fixtures (judgment-*.json) for why: this is what items 13-17 get validated against
// before any of them is trusted enough to promote from flag to gate.
const loadFixture = (filename) => JSON.parse(fs.readFileSync(path.join(FIXTURES_DIR, filename), 'utf8'));
const deterministicFixtures = allFixtureFiles.filter((f) => !('judgments' in loadFixture(f)));
const judgmentFixtures = allFixtureFiles.filter((f) => 'judgments' in loadFixture(f));

describe('document-checking regression fixtures (deterministic)', () => {
  it.each(deterministicFixtures)('%s', (filename) => {
    const fixture = loadFixture(filename);
    const result = evaluateDocumentChecks(fixture.extractedFields);

    expect(result.passed).toBe(fixture.expected.passed);
    expect(result.issues).toEqual(fixture.expected.issues);
    expect(result.flags.map((f) => f.code)).toEqual(fixture.expected.flagCodes);
    expect(result.flags).toEqual(fixture.expected.flags);
  });
});

describe('document-checking regression fixtures (judgment-dependent)', () => {
  it.each(judgmentFixtures)('%s', (filename) => {
    const fixture = loadFixture(filename);
    const result = evaluateJudgmentDependentChecks(fixture.extractedFields, fixture.judgments);

    expect(result.issues).toEqual(fixture.expected.issues);
    expect(result.flags.map((f) => f.code)).toEqual(fixture.expected.flagCodes);
  });
});

// Regression for the 2026-09-16 fix (case e5498fa0-28d3-46da-9d61-a4adb16b92f2): when stage 1
// already has an issue, service.js skips stage 2 (the LLM judgment calls, delegation letter
// included) entirely for cost reasons — this placeholder list is what fills that gap so
// those items don't just vanish from the checklist the console renders.
describe('pendingJudgmentChecklist', () => {
  it('lists every judgment-dependent code as not-yet-evaluated (passed: null)', () => {
    const items = pendingJudgmentChecklist();
    expect(items.map((i) => i.code)).toEqual([
      'DELEGATION_LETTER_REQUIRED',
      'DELEGATION_PAYEE_INCONSISTENT',
      'PATIENT_NAME_INCONSISTENT',
      'PROVIDER_NAME_INCONSISTENT',
      'HOSPITAL_NAME_INCONSISTENT',
      'DIAGNOSIS_TREATMENT_INCONSISTENT',
    ]);
    expect(items.every((i) => i.passed === null && i.label && i.note)).toBe(true);
  });
});
